"""
analytics_agent.py — Phase 2 update (fully AI-generated responses).
All fallbacks, suggested questions, personas, and error messages
are generated by Gemini — zero hardcoded content.
"""
import json
import structlog
import vertexai
from vertexai.generative_models import GenerativeModel, GenerationConfig

from services.persona_service import get_persona_prompt_injection
from services.chart_selector import select_chart_type, rows_to_chart_data, get_chart_description
from services.guardrail_service import strip_pii, validate_numbers_against_data
from config import settings

logger = structlog.get_logger()

ANALYTICS_SYSTEM = """You are a senior analytics AI for VODAFONE IRELAND — the market leader in Irish telecommunications.

CONTEXT: You analyse the Vodafone Ireland subscriber database (KarthikRudrapati BigQuery dataset).
COMPETITORS: Eir (~28% share), Three Ireland (~22%), Sky Ireland (~10%), GoMo/MVNOs (~8%)
MARKET: ~5.2M total Irish mobile subscribers. Vodafone holds ~32%.
BENCHMARKS: Mobile ARPU €18–22/month | Churn 15–18% annually | 5G coverage 80%+

CRITICAL RULES:
1. Only cite numbers that appear in the BQ data provided
2. Always say "Vodafone Ireland" not "Ireland Constellation" or "the company"
3. Suggested questions must reference actual dimension values seen in the data
4. Return ONLY valid JSON — no preamble, no markdown fences
5. Every KPI value and change must be a STRING (not integer)"""

ANALYTICS_PROMPT = """
{persona_context}

{history_context}

USER QUERY: {query}

BIGQUERY SCHEMA:
{schema}

QUERY RESULTS:
Current period: {current_data}
Previous period: {previous_data}
By dimensions: {dimensions_data}
Trend (6 months): {trend_data}

IRELAND MARKET CONTEXT:
{market_context}

Generate a comprehensive analytics response. Return ONLY this JSON:
{{
  "what_happened": "2-3 sentences. Start with exact subscriber/metric numbers from the data.",
  "kpis": [
    {{"label": "...", "value": "...", "change": "...", "trend": "up|down|neutral"}},
    {{"label": "...", "value": "...", "change": "...", "trend": "up|down|neutral"}},
    {{"label": "...", "value": "...", "change": "...", "trend": "up|down|neutral"}}
  ],
  "chart": {{
    "type": "{chart_type}",
    "title": "...",
    "auto_selected": true,
    "selection_reason": "{chart_reason}",
    "data": [{{"label": "...", "value": 0.0, "is_peak": false, "is_min": false}}]
  }},
  "root_causes": [
    {{"driver": "...", "detail": "...", "impact_pct": "±X%", "confidence_pct": "X%"}}
  ],
  "market_analysis": [
    {{"type": "Market", "icon": "🌍", "text": "Vodafone Ireland market position with competitor names"}}
  ],
  "competitor_analysis": [
    {{"operator": "Eir|Three Ireland|Sky Ireland|GoMo", "threat_level": "High|Medium|Low",
      "detail": "specific competitor action", "market_share": "X%"}}
  ],
  "recommendations": [
    {{"priority": "P1|P2", "action": "...", "type": "Tactical|Strategic",
      "timeline": "...", "expected_impact": "..."}}
  ],
  "risks": [
    {{"severity": "High|Medium|Low", "risk": "...", "mitigation": "..."}}
  ],
  "summary_bullets": ["bullet 1", "bullet 2", "bullet 3"],
  "suggested_questions": [
    "Question 1 using actual column/dimension values from the data",
    "Question 2 using actual values",
    "Question 3",
    "Question 4",
    "Question 5"
  ]
}}

IMPORTANT:
- All KPI values and changes must be STRINGS
- suggested_questions must be tailored to persona role: {persona_name}
- chart data must match the {chart_type} format
- Use exact numbers from the BQ results
- Competitor names must be: Eir, Three Ireland, Sky Ireland, GoMo, Virgin Media"""

FALLBACK_PROMPT = """You are a senior analytics AI for Vodafone Ireland.
An analytics pipeline error occurred for this query: "{query}"
Persona: {persona_name} ({persona_id})

Generate a helpful error response with AI-suggested follow-up questions tailored to the persona.
Return ONLY this JSON (no preamble, no markdown):
{{
  "what_happened": "Brief explanation that data could not be retrieved, suggest rephrasing.",
  "kpis": [],
  "chart": {{"type": "bar", "title": "No data available", "data": [], "auto_selected": true, "selection_reason": "No data"}},
  "root_causes": [],
  "market_analysis": [],
  "competitor_analysis": [],
  "recommendations": [
    {{"priority": "P1", "action": "Rephrase the query with a specific date range or metric", "type": "Tactical", "timeline": "Immediate", "expected_impact": "Successful data retrieval"}}
  ],
  "risks": [],
  "summary_bullets": ["Pipeline error occurred", "Please try a different query", "Check date range and metric names"],
  "suggested_questions": [
    "5 smart follow-up questions for a {persona_name} about Vodafone Ireland subscriber data"
  ]
}}"""

QUESTIONS_PROMPT = """You are an analytics AI for Vodafone Ireland.
Generate exactly 5 smart follow-up questions for a {persona_name} persona
based on this query: "{query}"
Available data dimensions: {dimensions}

Return ONLY a JSON array of 5 strings. No preamble, no markdown:
["question1", "question2", "question3", "question4", "question5"]"""

PERSONA_FALLBACK_PROMPT = """You are an analytics AI for Vodafone Ireland.
Generate a persona context injection string for persona_id="{persona_id}".
This will be inserted into an analytics prompt.
Return plain text (not JSON) describing the persona role, focus areas, KPIs and question style
for a Vodafone Ireland analytics dashboard user with role: {persona_id}."""


class AnalyticsAgent:

    def __init__(self):
        self._model = None

    def _get_model(self) -> GenerativeModel:
        if not self._model:
            vertexai.init(
                project=settings.GCP_PROJECT_ID,
                location=settings.GCP_LOCATION,
            )
            self._model = GenerativeModel(model_name=settings.VERTEX_AI_MODEL)
        return self._model

    async def _generate(self, prompt: str, max_tokens: int = 1000, temperature: float = 0.3) -> str:
        """Single reusable Gemini call."""
        model = self._get_model()
        response = await model.generate_content_async(
            prompt,
            generation_config=GenerationConfig(
                temperature=temperature,
                max_output_tokens=max_tokens,
            ),
        )
        return response.text.strip()

    async def _ai_persona_context(self, persona_id: str) -> str:
        """Generate persona context via Gemini if persona_service fails."""
        try:
            raw = await self._generate(
                PERSONA_FALLBACK_PROMPT.format(persona_id=persona_id),
                max_tokens=400,
            )
            return raw
        except Exception as e:
            logger.warning("AI persona generation failed", error=str(e))
            return f"USER PERSONA: {persona_id.title()}\nRole: Vodafone Ireland analytics user."

    async def _ai_suggested_questions(self, query: str, persona_id: str, persona_name: str, dim_rows: list) -> list:
        """Generate 5 suggested questions via Gemini."""
        try:
            dims = json.dumps([r for r in dim_rows[:10]], default=str) if dim_rows else "[]"
            raw = await self._generate(
                QUESTIONS_PROMPT.format(
                    persona_name=persona_name,
                    query=query,
                    dimensions=dims,
                ),
                max_tokens=300,
            )
            raw = raw.replace("```json", "").replace("```", "").strip()
            questions = json.loads(raw)
            if isinstance(questions, list) and len(questions) >= 1:
                return questions[:5]
        except Exception as e:
            logger.warning("AI questions generation failed", error=str(e))
        return []

    async def _ai_fallback_result(self, query: str, persona_id: str, persona_name: str) -> dict:
        """Generate a full fallback result via Gemini instead of hardcoded strings."""
        try:
            raw = await self._generate(
                FALLBACK_PROMPT.format(
                    query=query,
                    persona_id=persona_id,
                    persona_name=persona_name,
                ),
                max_tokens=800,
            )
            raw = raw.replace("```json", "").replace("```", "").strip()
            result = json.loads(raw)
            if isinstance(result, dict):
                return result
        except Exception as e:
            logger.error("AI fallback generation failed", error=str(e))

        # Absolute last resort — minimal structure with AI questions
        questions = await self._ai_suggested_questions(query, persona_id, persona_name, [])
        return {
            "what_happened": f"Unable to retrieve analytics data for: '{query}'. Please try rephrasing with a specific date range or metric name.",
            "kpis": [],
            "chart": {"type": "bar", "title": "No data available", "data": [], "auto_selected": True, "selection_reason": "No data"},
            "root_causes": [],
            "market_analysis": [],
            "competitor_analysis": [],
            "recommendations": [],
            "risks": [],
            "summary_bullets": [],
            "suggested_questions": questions,
        }

    async def run(self, context: dict) -> dict:
        """
        Run the analytics agent with persona awareness and smart chart selection.
        All responses — including errors and fallbacks — are AI-generated.
        """
        query           = context.get("query", "") or ""
        schema          = context.get("schema_text", "") or ""
        current_data    = json.dumps(context.get("current_data") or [])[:800]
        previous_data   = json.dumps(context.get("previous_data") or [])[:600]
        dimensions_data = json.dumps(context.get("dimensions_data") or [])[:800]
        trend_data      = json.dumps(context.get("trend_data") or [])[:600]
        market_context  = context.get("market_context", "") or ""
        persona_id      = context.get("persona_id", "analyst") or "analyst"
        persona_name    = context.get("persona_name", "Analyst") or "Analyst"
        history_ctx     = context.get("history_context", "") or ""

        # Persona context — try persona_service first, AI-generate if it fails
        try:
            persona_context = get_persona_prompt_injection(persona_id)
            if not persona_context:
                logger.warning("Persona service returned empty, generating via AI", persona_id=persona_id)
                persona_context = await self._ai_persona_context(persona_id)
        except Exception as e:
            logger.warning("Persona service failed, generating via AI", error=str(e))
            persona_context = await self._ai_persona_context(persona_id)

        # Chart type selection
        try:
            raw_rows = context.get("chart_data") or []
            chart_type = select_chart_type(
                query=query,
                rows=raw_rows,
                requested_type="kpi_card" if context.get("metric_semantics") == "snapshot" and len(raw_rows) <= 1 else None,
            )
            chart_reason = get_chart_description(chart_type)
        except Exception as e:
            logger.warning("Chart selection failed", error=str(e))
            raw_rows     = []
            chart_type   = "bar"
            chart_reason = "bar"

        prompt = ANALYTICS_PROMPT.format(
            persona_context = persona_context,
            history_context = f"CONVERSATION HISTORY:\n{history_ctx}" if history_ctx else "",
            query           = query,
            schema          = schema[:1500],
            current_data    = current_data,
            previous_data   = previous_data,
            dimensions_data = dimensions_data,
            trend_data      = trend_data,
            market_context  = market_context[:600],
            chart_type      = chart_type,
            chart_reason    = chart_reason,
            persona_name    = persona_name,
        )

        full_prompt = f"{ANALYTICS_SYSTEM}\n\n{prompt}"

        try:
            raw = await self._generate(full_prompt, max_tokens=3000, temperature=0.2)

            if raw.startswith("```"):
                raw = raw.split("\n", 1)[-1].rsplit("```", 1)[0].strip()

            result = json.loads(raw)

            if not isinstance(result, dict):
                logger.error("Analytics result is not a dict", type=type(result).__name__)
                context["analytics_result"] = await self._ai_fallback_result(query, persona_id, persona_name)
                return context

            # Post-processing
            if "chart" in result and isinstance(result["chart"], dict):
                result["chart"]["type"]             = chart_type
                result["chart"]["auto_selected"]    = True
                result["chart"]["selection_reason"] = chart_reason
                if raw_rows:
                    try:
                        result["chart"]["data"] = rows_to_chart_data(raw_rows, chart_type)
                    except Exception as e:
                        logger.warning("Chart data formatting failed", error=str(e))

            # Number validation
            try:
                all_rows = (
                    (context.get("current_data") or []) +
                    (context.get("dimensions_data") or []) +
                    (context.get("trend_data") or [])
                )
                validated = validate_numbers_against_data(result, all_rows)
                if isinstance(validated, dict):
                    result = validated
            except Exception as e:
                logger.warning("Number validation failed, skipping", error=str(e))

            # Canonical snapshot KPI: the value comes from the deterministic
            # BigQuery result, not from Gemini's generated prose. This prevents
            # the KPI card and chart from disagreeing for subscriber-count queries.
            if context.get("metric_semantics") == "snapshot":
                current_rows = context.get("current_data") or []
                if current_rows:
                    try:
                        value = next(iter(current_rows[0].values()))
                        if value is not None:
                            numeric_value = float(value)
                            result["kpis"] = [
                                {
                                    "label": "Subscriber Count",
                                    "value": f"{numeric_value:,.0f}",
                                    "change": result.get("kpis", [{}])[0].get("change", "N/A") if result.get("kpis") else "N/A",
                                    "trend": result.get("kpis", [{}])[0].get("trend", "neutral") if result.get("kpis") else "neutral",
                                },
                                *[k for k in (result.get("kpis") or [])[1:3]],
                            ]
                            if result.get("chart") is not None:
                                result["chart"]["data"] = rows_to_chart_data(
                                    context.get("chart_data") or current_rows, chart_type
                                )
                    except (TypeError, ValueError, StopIteration) as exc:
                        logger.warning("Canonical subscriber KPI formatting failed", error=str(exc))

            # PII stripping
            cleaned_bullets = []
            for bullet in result.get("summary_bullets") or []:
                try:
                    cleaned_bullets.append(strip_pii(bullet) if bullet else bullet)
                except Exception:
                    cleaned_bullets.append(bullet)
            result["summary_bullets"] = cleaned_bullets

            # AI-generate suggested questions if Gemini didn't return enough
            questions = result.get("suggested_questions") or []
            if len(questions) < 5:
                logger.info("Generating additional questions via AI", have=len(questions))
                ai_questions = await self._ai_suggested_questions(
                    query, persona_id, persona_name,
                    context.get("dimensions_data") or []
                )
                questions = (questions + ai_questions)[:5]
                result["suggested_questions"] = questions

            logger.info("Analytics complete",
                        persona=persona_id,
                        chart_type=chart_type,
                        kpis=len(result.get("kpis") or []))

            context["analytics_result"] = result
            return context

        except json.JSONDecodeError as e:
            logger.error("Analytics JSON parse failed", error=str(e)[:80])
            context["analytics_result"] = await self._ai_fallback_result(query, persona_id, persona_name)
            return context
        except Exception as e:
            logger.error("AnalyticsAgent failed", error=str(e)[:120])
            context["analytics_result"] = await self._ai_fallback_result(query, persona_id, persona_name)
            return context
