"""
BigQuery service — executes SQL generated by the Data Agent.
"""
import structlog
from google.cloud import bigquery
from config import settings

logger = structlog.get_logger()
_client: bigquery.Client | None = None


def get_bq_client() -> bigquery.Client:
    global _client
    if _client is None:
        _client = bigquery.Client(project=settings.GCP_PROJECT_ID)
    return _client


async def run_query(sql: str, max_rows: int = 1000) -> list[dict]:
    """
    Execute a SQL query against BigQuery and return rows as list of dicts.
    Raises on query error — callers should handle.
    """
    client = get_bq_client()
    logger.info("Running BigQuery query", sql_preview=sql[:120])
    try:
        job = client.query(sql)
        rows = job.result(max_results=max_rows)
        result = [dict(row) for row in rows]
        logger.info("BigQuery query complete", row_count=len(result))
        return result
    except Exception as e:
        logger.error("BigQuery error", error=str(e), sql=sql[:200])
        raise


async def list_tables(dataset_id: str) -> list[str]:
    """Return all table names in a BigQuery dataset."""
    client = get_bq_client()
    tables = client.list_tables(f"{settings.GCP_PROJECT_ID}.{dataset_id}")
    return [t.table_id for t in tables]


async def get_table_schema(dataset_id: str, table_id: str) -> list[dict]:
    """Return column names and types for a table."""
    client = get_bq_client()
    table = client.get_table(f"{settings.GCP_PROJECT_ID}.{dataset_id}.{table_id}")
    return [{"name": f.name, "type": f.field_type, "description": f.description or ""} for f in table.schema]
